name: Build markdown files by code files and deploy with Mkdocs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - run: |
          git clone https://${GH_TOKEN}@github.com/mashafrancis/dsa-mkdocs.git mkdocs
          git clone https://${GH_TOKEN}@github.com/mashafrancis/dsa-scripts.git scripts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - run: pip install gspread
      - run: pip install oauth2client

      - name: Rebase commits
        run: |
          git config --global user.email "${EMAIL}"
          git config --global user.name "mashafrancis"
          git checkout --orphan temp
          git add .github solutions *.md
          git commit -m 'rebase dsa'
          git branch -D main
          git branch -m main
          git push origin main -f
        env:
          EMAIL: ${{ secrets.EMAIL }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r scripts/requirements.txt

      - run: cp README.md mkdocs/docs/index.md
      - run: cp NAMING.md mkdocs/docs/naming.md

      - name: Mkdocs builds mkdocs/docs to mkdocs/site
        run: |
          cd mkdocs
          mkdocs build
          cd ..

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: mkdocs/site
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'